fix: clean translations before pulling them (#1026)
If one is using a bind-mounted edx-platform directory,
they may already have pulled translations. This will cause
the Docker build to fail with:

    CommandError: "/openedx/edx-platform/conf/plugins-locale/plugins" should be empty before running atlas pull.

To fix this, we simply clean out the edx-platform translation
target directories before pulling in the Dockerfile.